// Stellar testnet deployment config for the Agama POC.
// Generated by smart/soroban/scripts/deploy.sh and copied to deployments.testnet.json.
import deployment from './deployments.testnet.json';

export const STELLAR = {
  network: deployment.network,
  passphrase: deployment.networkPassphrase,
  rpcUrl: deployment.rpcUrl,
  admin: deployment.admin,
  treasury: deployment.treasury,
  decimals: deployment.decimals,
  cooldownSeconds: deployment.cooldownSeconds,
  contracts: deployment.contracts as {
    usdc: string;
    agusd: string;
    staking: string;
  },
  // One on-chain vault per curated credit vault (3 Qiro + 3 Tenka), USDC-denominated.
  creditVaults: deployment.creditVaults as Record<string, string>,
  // Real Circle USDC on Stellar testnet (classic asset via its Stellar Asset Contract).
  usdcIssuer: (deployment as { usdcIssuer?: string }).usdcIssuer ?? '',
  usdcReal: (deployment as { usdcReal?: boolean }).usdcReal ?? false,
} as const;

export const STELLAR_DECIMALS = STELLAR.decimals; // 7
export const SHARE_PRICE_SCALE = 10 ** STELLAR.decimals; // 1.0 share price

// Block explorer for contracts / accounts on testnet.
export const explorerContract = (id: string) =>
  `https://stellar.expert/explorer/testnet/contract/${id}`;
export const explorerAccount = (addr: string) =>
  `https://stellar.expert/explorer/testnet/account/${addr}`;
export const explorerTx = (hash: string) =>
  `https://stellar.expert/explorer/testnet/tx/${hash}`;
