// Agama x Arrow on X Layer Testnet. Addresses come from the Foundry
// deployment (deployments/1952.json), regenerated by scripts/sync-xlayer.mjs.
import { defineChain, stringToHex } from 'viem';

import { deployments } from './generated/deployments';

// X Layer Testnet by default. Pointing this at a local anvil fork of X Layer
// (chain 1961) is how the browser flows get tested without spending testnet
// gas, which a public faucet rations:
//   NEXT_PUBLIC_XLAYER_CHAIN_ID=1961 NEXT_PUBLIC_XLAYER_RPC=http://127.0.0.1:8545 pnpm dev
// The fork deployment only reaches the bundle when the sync is asked for it
// (INCLUDE_FORK_DEPLOYMENTS=1), so a production build can never show a wallet
// addresses that exist on one laptop.
export const CHAIN_ID = Number(process.env.NEXT_PUBLIC_XLAYER_CHAIN_ID ?? 1952);
export const CHAIN_ID_HEX = `0x${CHAIN_ID.toString(16)}`;
const IS_FORK = CHAIN_ID === 1961;
const RPC_URL =
  process.env.NEXT_PUBLIC_XLAYER_RPC ||
  (IS_FORK ? 'http://127.0.0.1:8545' : 'https://testrpc.xlayer.tech/terigon');

export const xLayerTestnet = defineChain({
  id: CHAIN_ID,
  name: IS_FORK ? 'X Layer (local fork)' : 'X Layer Testnet',
  nativeCurrency: { name: 'OKB', symbol: 'OKB', decimals: 18 },
  rpcUrls: { default: { http: [RPC_URL] } },
  blockExplorers: {
    default: { name: 'OKX Explorer', url: 'https://www.okx.com/web3/explorer/xlayer-test' },
  },
  // Deployed at the canonical address on X Layer, checked on testnet. Without
  // it every refresh is about thirty separate calls to a public RPC that
  // rate limits, which shows up as prices that flicker in and out.
  contracts: { multicall3: { address: '0xcA11bde05977b3631167028862bE2a173976CA11' } },
  testnet: true,
});

const found = deployments[CHAIN_ID];
if (!found) throw new Error(`no deployment for chain ${CHAIN_ID} in lib/xlayer/generated`);
export const D = found;
export const ADDR = D.contracts;
export const TOKENS = D.tokens;
export const ADAPTERS = D.adapters;

export const EXPLORER = xLayerTestnet.blockExplorers.default.url;

/// A file from this app's own public/. app.agama.finance proxies this app and
/// serves its own public/ on that path, so anything only we have (the X Layer
/// mark) must be fetched from where it actually exists.
export const asset = (path: string) => `${process.env.NEXT_PUBLIC_ASSET_PREFIX ?? ''}${path}`;
export const OKB_FAUCET = 'https://web3.okx.com/xlayer/faucet';

export const USDG_DECIMALS = 6;
export const STOCK_DECIMALS = 18;
export const BPS = 10_000n;
export const RAY = 10n ** 27n;
/// The vault keeps 18 decimals over a 6-decimal USDG, so its assets are agUSD.
export const AG_PER_USDG = 10n ** 12n;

export type StockKey = 'TSLA' | 'NVDA' | 'SPY' | 'AAPL';

export interface Stock {
  key: StockKey;
  /// The ERC-4626 wrapper the lending markets take. An implementation detail:
  /// the app speaks the base token, which is what OKX sends and accepts.
  wrapper: 'wTSLAx' | 'wNVDAx' | 'wSPYx' | 'wAAPLx';
  /// What a withdrawal from the OKX app delivers, and the only name shown.
  base: 'TSLAx' | 'NVDAx' | 'SPYx' | 'AAPLx';
  name: string;
  ticker: `0x${string}`; // bytes32, right padded
}

export const STOCKS: Stock[] = [
  { key: 'TSLA', wrapper: 'wTSLAx', base: 'TSLAx', name: 'Tesla', ticker: stringToHex('TSLA', { size: 32 }) },
  { key: 'NVDA', wrapper: 'wNVDAx', base: 'NVDAx', name: 'NVIDIA', ticker: stringToHex('NVDA', { size: 32 }) },
  { key: 'SPY', wrapper: 'wSPYx', base: 'SPYx', name: 'S&P 500 ETF', ticker: stringToHex('SPY', { size: 32 }) },
  { key: 'AAPL', wrapper: 'wAAPLx', base: 'AAPLx', name: 'Apple', ticker: stringToHex('AAPL', { size: 32 }) },
];

/// Shown until the vault has two NAV snapshots to measure a realized APY from.
export const TARGET_VAULT_APY_RAY = 10n ** 26n; // 10%
