// Agama x Arrow on X Layer Testnet. Addresses come from the Foundry
// deployment (deployments/1952.json), regenerated by scripts/sync-xlayer.mjs.
import { defineChain, stringToHex } from 'viem';

import { deployments } from './generated/deployments';

// X Layer Testnet by default. Pointing this at a local anvil fork of X Layer
// (chain 1961) is how the browser flows get tested without spending testnet
// gas, which a public faucet rations:
//   NEXT_PUBLIC_XLAYER_CHAIN_ID=1961 NEXT_PUBLIC_XLAYER_RPC=http://127.0.0.1:8545 pnpm dev
// The fork deployment only reaches the bundle when the sync is asked for it
// (INCLUDE_FORK_DEPLOYMENTS=1), so a production build can never show a wallet
// addresses that exist on one laptop.
export const CHAIN_ID = Number(process.env.NEXT_PUBLIC_XLAYER_CHAIN_ID ?? 1952);
export const CHAIN_ID_HEX = `0x${CHAIN_ID.toString(16)}`;
const IS_FORK = CHAIN_ID === 1961;
const RPC_URL =
  process.env.NEXT_PUBLIC_XLAYER_RPC ||
  (IS_FORK ? 'http://127.0.0.1:8545' : 'https://testrpc.xlayer.tech/terigon');

export const xLayerTestnet = defineChain({
  id: CHAIN_ID,
  name: IS_FORK ? 'X Layer (local fork)' : 'X Layer Testnet',
  nativeCurrency: { name: 'OKB', symbol: 'OKB', decimals: 18 },
  rpcUrls: { default: { http: [RPC_URL] } },
  blockExplorers: {
    default: { name: 'OKX Explorer', url: 'https://www.okx.com/web3/explorer/xlayer-test' },
  },
  testnet: true,
});

const found = deployments[CHAIN_ID];
if (!found) throw new Error(`no deployment for chain ${CHAIN_ID} in lib/xlayer/generated`);
export const D = found;
export const ADDR = D.contracts;
export const TOKENS = D.tokens;
export const ADAPTERS = D.adapters;

export const EXPLORER = xLayerTestnet.blockExplorers.default.url;
export const OKB_FAUCET = 'https://web3.okx.com/xlayer/faucet';

export const USDG_DECIMALS = 6;
export const STOCK_DECIMALS = 18;
export const BPS = 10_000n;
export const RAY = 10n ** 27n;

export type StockKey = 'TSLA' | 'NVDA' | 'SPY' | 'AAPL';

export interface Stock {
  key: StockKey;
  wrapper: 'wTSLAx' | 'wNVDAx' | 'wSPYx' | 'wAAPLx';
  name: string;
  ticker: `0x${string}`; // bytes32, right padded
}

export const STOCKS: Stock[] = [
  { key: 'TSLA', wrapper: 'wTSLAx', name: 'Tesla', ticker: stringToHex('TSLA', { size: 32 }) },
  { key: 'NVDA', wrapper: 'wNVDAx', name: 'NVIDIA', ticker: stringToHex('NVDA', { size: 32 }) },
  { key: 'SPY', wrapper: 'wSPYx', name: 'S&P 500 ETF', ticker: stringToHex('SPY', { size: 32 }) },
  { key: 'AAPL', wrapper: 'wAAPLx', name: 'Apple', ticker: stringToHex('AAPL', { size: 32 }) },
];

/// Shown until the vault has two NAV snapshots to measure a realized APY from.
export const TARGET_VAULT_APY_RAY = 10n ** 26n; // 10%
