// Agama x Arrow on X Layer Testnet. Addresses come from the Foundry
// deployment (deployments/1952.json), regenerated by scripts/sync-xlayer.mjs.
import { defineChain, stringToHex } from 'viem';

import { deployments } from './generated/deployments';

export const CHAIN_ID = 1952;
export const CHAIN_ID_HEX = '0x7a0';

export const xLayerTestnet = defineChain({
  id: CHAIN_ID,
  name: 'X Layer Testnet',
  nativeCurrency: { name: 'OKB', symbol: 'OKB', decimals: 18 },
  rpcUrls: { default: { http: ['https://testrpc.xlayer.tech/terigon'] } },
  blockExplorers: {
    default: { name: 'OKX Explorer', url: 'https://www.okx.com/web3/explorer/xlayer-test' },
  },
  testnet: true,
});

const found = deployments[CHAIN_ID];
if (!found) throw new Error('no X Layer Testnet deployment in lib/xlayer/generated');
export const D = found;
export const ADDR = D.contracts;
export const TOKENS = D.tokens;
export const ADAPTERS = D.adapters;

export const EXPLORER = xLayerTestnet.blockExplorers.default.url;
export const OKB_FAUCET = 'https://web3.okx.com/xlayer/faucet';

export const USDG_DECIMALS = 6;
export const STOCK_DECIMALS = 18;
export const BPS = 10_000n;
export const RAY = 10n ** 27n;

export type StockKey = 'TSLA' | 'NVDA' | 'SPY' | 'AAPL';

export interface Stock {
  key: StockKey;
  wrapper: 'wTSLAx' | 'wNVDAx' | 'wSPYx' | 'wAAPLx';
  name: string;
  ticker: `0x${string}`; // bytes32, right padded
}

export const STOCKS: Stock[] = [
  { key: 'TSLA', wrapper: 'wTSLAx', name: 'Tesla', ticker: stringToHex('TSLA', { size: 32 }) },
  { key: 'NVDA', wrapper: 'wNVDAx', name: 'NVIDIA', ticker: stringToHex('NVDA', { size: 32 }) },
  { key: 'SPY', wrapper: 'wSPYx', name: 'S&P 500 ETF', ticker: stringToHex('SPY', { size: 32 }) },
  { key: 'AAPL', wrapper: 'wAAPLx', name: 'Apple', ticker: stringToHex('AAPL', { size: 32 }) },
];

/// Shown until the vault has two NAV snapshots to measure a realized APY from.
export const TARGET_VAULT_APY_RAY = 10n ** 26n; // 10%
