#!/usr/bin/env node
// Copies deployments/*.json and the ABIs the front needs from the Foundry
// artifacts (../out) into lib/generated/*.ts, as typed `as const` modules.
//
// Runs before `dev` and `build`. If ../out or ../deployments is missing
// (fresh clone, CI, Vercel), the previously generated files are kept so the
// build still works: lib/generated is meant to be committed.

import {existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = join(here, "..");
const repoRoot = join(appRoot, "..");
const outDir = join(repoRoot, "out");
const deploymentsDir = join(repoRoot, "deployments");
const genDir = join(appRoot, "lib", "generated");

mkdirSync(genDir, {recursive: true});

const HEADER = "// AUTO-GENERATED by scripts/sync.mjs. Do not edit by hand.\n";

// [exportName, artifact file, contract name]
const ABIS = [
  ["earnRouterAbi", "AgamaEarnRouter.sol", "AgamaEarnRouter"],
  ["amplifyRouterAbi", "AgamaAmplifyRouter.sol", "AgamaAmplifyRouter"],
  ["accountAbi", "AgamaAccount.sol", "AgamaAccount"],
  ["accountFactoryAbi", "AgamaAccountFactory.sol", "AgamaAccountFactory"],
  ["lendingPoolAbi", "ArrowLendingPool.sol", "ArrowLendingPool"],
  ["stabilityPoolAbi", "ArrowStabilityPool.sol", "ArrowStabilityPool"],
  ["xStockAdapterAbi", "ArrowXStockAdapter.sol", "ArrowXStockAdapter"],
  ["vaultShareAdapterAbi", "ArrowVaultShareAdapter.sol", "ArrowVaultShareAdapter"],
  ["stockOracleAbi", "DataStreamsStockOracle.sol", "DataStreamsStockOracle"],
  ["sagUsdAbi", "sagUSD.sol", "sagUSD"],
  ["agUsdQueueAbi", "agUSDQueue.sol", "agUSDQueue"],
  ["debtTokenAbi", "DebtToken.sol", "DebtToken"],
];

// ---- ABIs ---------------------------------------------------------------------

if (existsSync(outDir)) {
  const errors = new Map();
  let src = HEADER;
  let ok = true;
  for (const [name, file, contract] of ABIS) {
    const p = join(outDir, file, `${contract}.json`);
    if (!existsSync(p)) {
      console.warn(`[sync] missing artifact ${p}, keeping the previous abis.ts`);
      ok = false;
      break;
    }
    const abi = JSON.parse(readFileSync(p, "utf8")).abi;
    for (const item of abi) {
      if (item.type !== "error") continue;
      const sig = `${item.name}(${item.inputs.map((i) => i.type).join(",")})`;
      if (!errors.has(sig)) errors.set(sig, item);
    }
    src += `\nexport const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  }
  if (ok) {
    // Every custom error of the stack, used to decode reverts that bubble up
    // from nested calls (pool, adapters, oracle, vault) through the routers.
    src += `\nexport const allErrorsAbi = ${JSON.stringify([...errors.values()], null, 2)} as const;\n`;
    writeFileSync(join(genDir, "abis.ts"), src);
    console.log(`[sync] abis.ts: ${ABIS.length} contracts, ${errors.size} errors`);
  }
} else if (existsSync(join(genDir, "abis.ts"))) {
  console.log("[sync] ../out not found, keeping the committed abis.ts");
} else {
  console.error("[sync] ../out not found and no committed abis.ts. Run `forge build` in the repo root.");
  process.exit(1);
}

// ---- Deployments -----------------------------------------------------------------

if (existsSync(deploymentsDir)) {
  const all = {};
  for (const f of readdirSync(deploymentsDir)) {
    const m = /^(\d+)\.json$/.exec(f);
    if (!m) continue;
    const d = JSON.parse(readFileSync(join(deploymentsDir, f), "utf8"));
    all[m[1]] = d;
  }
  const src =
    HEADER +
    `import type {Deployment} from "../deployment-types";\n\n` +
    `export const deployments: Partial<Record<number, Deployment>> = ${JSON.stringify(all, null, 2)};\n`;
  writeFileSync(join(genDir, "deployments.ts"), src);
  console.log(`[sync] deployments.ts: chains ${Object.keys(all).join(", ") || "(none)"}`);
} else if (existsSync(join(genDir, "deployments.ts"))) {
  console.log("[sync] ../deployments not found, keeping the committed deployments.ts");
} else {
  writeFileSync(
    join(genDir, "deployments.ts"),
    HEADER +
      `import type {Deployment} from "../deployment-types";\n\nexport const deployments: Partial<Record<number, Deployment>> = {};\n`,
  );
  console.log("[sync] no deployments found, wrote an empty deployments.ts");
}
